spring:
  application:
    name: project-two
  jackson:
    default-property-inclusion: non_null
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""